# Generated by Django 3.1.4 on 2020-12-07 15:19

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='0b806426e8', unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='street_address2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
